### ISSUE TITLE
Provide config file to let users config color

### ISSUE THREAD

**Issue by laike9m** [laike9m/pdir2#14]
Including disable coloring.

**Comment by laike9m** [comment]
@novel-yet-trivial @Chovin @okken
As of 0.2.0, I've added color customization to pdir2. Hope it works for you guys.

**Comment by okken** [comment]
Cool. Can't wait to try. 
- Brian

**Comment by okken** [comment]
Maybe I'm dense. 
How do I change the color?
- Brian

**Comment by laike9m** [comment]
@okken Here you go
https://github.com/laike9m/pdir2/wiki/User-Configuration
