### ISSUE TITLE
Does it work in jupyter notebooks?

### ISSUE THREAD

**Issue by lincolnfrias** [laike9m/pdir2#26]
I can get it to work on ipython, but not on the notebook. 

Should I run any extra command?

Thanks for the awesome work.

**Comment by laike9m** [comment]
Sorry, I didn't test on jupyter framework. The not printing issue should be easy to fix if I can differentiate ipython and jupyter notebook. However, color printing is harder. I need to try those solutions in http://stackoverflow.com/questions/16816013/is-it-possible-to-print-using-different-color-in-ipythons-notebook.

**Comment by lincolnfrias** [comment]
Nice, thanks for answering. Unfortunately this is way beyond my understanding, but I am patient. :)

**Comment by laike9m** [comment]
@lincolnfrias It should work on jupyter notebooks now.

**Comment by lincolnfrias** [comment]
Yes, it works! Awesome. Thanks a lot!
