### ISSUE TITLE
minimum setuptools version

### ISSUE THREAD

**Issue by carlwgeorge** [laike9m/pdir2#31]
Currently the setup.py file is using [environment markers](https://www.python.org/dev/peps/pep-0496/) to define the [colorama and enum34 dependencies](https://github.com/laike9m/pdir2/blob/v0.2.0/setup.py#L19-L20).  Those are only present in setuptools 20.6.8 or newer.  There are a two ways we can handle this (I can do an appropriate pull request once I know which one you prefer).

1. Remove the environment marks and dynamically generate the requirements list.

```python
requirements = []
if platform.system == 'Windows':
    requirements.append('colorama')
if sys.version_info[:2] < (3, 4):
    requirements.append('enum34')
```
```python
    install_requires=requirements,
```

2. Document the minimum setuptools version needed in the `setup_requires` parameter of the `setup` function.

```python
    setup_requires=['setuptools>=20.6.8'],
```

**Comment by laike9m** [comment]
I'll go with the second approach.
