### ISSUE TITLE
frozenset error ,SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by wanyaoqi** [laike9m/pdir2#34]
I'm install the pdir2 from pip, when import pdir ,get error : 

  File "/usr/lib/python2.6/site-packages/pdir/constants.py", line 257
    BLACK, BRIGHT_BLACK, RED, BRIGHT_RED, GREEN, BRIGHT_GREEN,
         ^
SyntaxError: invalid syntax

And found /usr/lib/python2.6/site-packages/pdir/constants.py
VALID_COLORS = frozenset({
    BLACK, BRIGHT_BLACK, RED, BRIGHT_RED, GREEN, BRIGHT_GREEN,
    YELLOW, BRIGHT_YELLOW, BLUE, BRIGHT_BLUE, MAGENTA, BRIGHT_MAGENTA,
    CYAN, BRIGHT_CYAN, WHITE, BRIGHT_WHITE})

i fix it : 
VALID_COLORS = frozenset([
    BLACK, BRIGHT_BLACK, RED, BRIGHT_RED, GREEN, BRIGHT_GREEN,
    YELLOW, BRIGHT_YELLOW, BLUE, BRIGHT_BLUE, MAGENTA, BRIGHT_MAGENTA,
    CYAN, BRIGHT_CYAN, WHITE, BRIGHT_WHITE])

and import pdir is good.

**Comment by laike9m** [comment]
You're right. I didn't test under Python 2.6. You can create a PR if you like.
