### ISSUE TITLE
Support more repls

### ISSUE THREAD

**Issue by caedn** [laike9m/pdir2#4]
Specifically ptpython, as mentioned on [reddit](https://www.reddit.com/r/Python/comments/5ykbef/wrote_a_new_tool_that_makes_beautiful_dir_output/dera5ta/).

**Comment by laike9m** [comment]
Sure, this is in my plan. Stay tuned.

**Comment by laike9m** [comment]
Should be compatible with [ipython](https://github.com/ipython/ipython), [ptpython](https://github.com/jonathanslenders/ptpython) and [bpython](https://www.bpython-interpreter.org/).

**Comment by novel-yet-trivial** [comment]
Some colors are very hard to read for me. Especially grey, probably because of my semi transparent terminal. Maybe make a way to 'theme' colors. A config file for instance.

**Comment by laike9m** [comment]
@novel-yet-trivial Sure, there will be config file. It's on the TODO list.

**Comment by Congee** [comment]
``` Python
>>> import pdir
>>> old_repr = pdir.__repr__
>>> def new_repr(x):
...     print(old_repr(x))
...     return ''
>>> pdir.__repr__ = new_repr
>>> pdir(pdir)
```

This works for me in ptpython

**Comment by laike9m** [comment]
@Congee Exactly, I'm trying very hard to get pdir2 working in ptpython, and it's just too hard(ptpython manipulates output over and over before finally printing it). The simplest workaround is to print the result then return '' in `__repr__`, but that leads to another problem that you can't assign the result of `pdir()` to a variable.

I'm still working on this. Hope I can find a nice solution.

**Comment by caedn** [comment]
Just saw your commit. So far it works great with ptpython. One little bug: The `Out[n]: ` prompt is tacked onto the end instead of being in front of the output (in ipython it's at the correct position).

**Comment by laike9m** [comment]
could you take a screenshot of it?

**Comment by caedn** [comment]
Here you go, this is ptpython:

![image](https://cloud.githubusercontent.com/assets/23618713/23891282/d486cf30-0895-11e7-9cb0-f6c021aea11e.png)

ipython works fine:

![image](https://cloud.githubusercontent.com/assets/23618713/23891318/f80b05ca-0895-11e7-9d7f-62ebc7db4b0f.png)

**Comment by laike9m** [comment]
Thanks, gonna fix it when I get home.

**Comment by laike9m** [comment]
@caedn I can't reproduce the error, I tried `ptpython`,`ptpython3`,`ptipython`,`ptipython3`, none of them gave the result as yours. Could you tell me the Python version, ptpython version and command you use?

**Comment by caedn** [comment]
Stable CPython 3.6.0 and ptpython version: 0.36. I removed both `.pythonstartup` and `.ptpython/config.py`, then set the ptpython prompt to `ipython` (press `F2` to get the menu) and got the same result.

I'm on macOS Sierra 10.12.3. 

```python
caedn:~:$ ptpython3                                                                                                                                                                         0
In [1]: import pdir
In [2]: pdir(pdir)
attribute access:
    __delattr__, __dir__, __getattribute__, __setattr__
class customization:
    __init_subclass__, __subclasshook__
emulating container:
    __getitem__, __len__
object customization:
    __format__, __hash__, __init__, __new__, __repr__, __sizeof__, __str__
other:
    repr_str
pickle:
    __reduce__, __reduce_ex__
rich comparison:
    __eq__, __ge__, __gt__, __le__, __lt__, __ne__
special attribute:
    __class__, __dict__, __doc__, __module__, __weakref__
function:
    _PrettyDir__getattr_wrapper: A wrapper around getattr(), handling some exceptions.
    _PrettyDir__inspect_category:
    _is_non_standard_repl:
    get_category:
    get_oneline_doc:
    s: Search for names that match some pattern.
    search: Search for names that match some pattern.Out[2]:
```

**Comment by laike9m** [comment]
I believe this is a problem of ptpython, because ipython will put `Out[2]` in front of the printed text. I'll open an issue there, see if it's possible for them to fix it.

**Comment by Chovin** [comment]
is this issue no longer about adding a config option to disable coloring?
I would still love to see that option and is actually the deciding factor of whether or not I will use this package

**Comment by laike9m** [comment]
@Chovin No it's not. See #14.

**Comment by laike9m** [comment]
As of release [0.1.0](https://github.com/laike9m/pdir2/releases), pdir2 support ipython, ptpython and bpython. Issue closed.

@Chovin If you have any suggestions about user configuration, we could continue our discussion in #14.
