### ISSUE TITLE
enum.auto import fails for python < 3.6

### ISSUE THREAD

**Issue by Mome** [laike9m/pdir2#54]
Hello,

I just tried to use pdir2 in Python 3.5, it fails to import `enum.auto`, which was only added in 3.6.

A workaround for me is to replace auto in attr_category.py with a function that returns incrementing integers:

``` python
try:
    from enum import auto
except ImportError:
    from itertools import count
    _auto_iter = count()
    auto = lambda : next(_auto_iter)
```

I dont know if this breaks something.

**Comment by laike9m** [comment]
This is a bug, but since Python 3.5 has reached the [end of life](https://stackoverflow.com/a/58999007/2142577), and people should be using Python >= 3.6, I will not fix it. Still, thanks for the bug report.
