### ISSUE TITLE
KeyError when formatting certain CATEGORIES

### ISSUE THREAD

**Issue by iamgodot** [laike9m/pdir2#60]
## Bug case

Currently the `_FORMATTER` in `format.py` misses three categories defined in `AttrCategory` enums, which will easily break the code during formatting, for instance:

```python
import pdir
from collections import namedtuple

Person = namedtuple('Person', 'name age')
pdir(Person)
```

The direct cause comes from one of `Person.__class_getitem__`, which falls into category `TYPING`, tand he other two missing categories are `SLOT` and `PATTERN_MATCHING`.

## Fix proposal

One easy way would be add a default formatter when getting from `_FORMATTER`. On the other hand, this `_FORMATTER` dict seems a bit redundant, so do the `ATTR_MAP` in `attr_category.py`(IMHO).

**Comment by laike9m** [comment]
Thanks for the bug report. Looks like you already have an idea on the fix, interested in creating a PR? I'll happily review it.

**Comment by iamgodot** [comment]
> Thanks for the bug report. Looks like you already have an idea on the fix, interested in creating a PR? I'll happily review it.

Sure, it's [here](https://github.com/laike9m/pdir2/pull/62), please let me know if I need to change anything :)

**Comment by iamgodot** [comment]
Great, I'll close this now.
