### ISSUE TITLE
Drop support for Python 2

### ISSUE THREAD

**Issue by aqeelat** [laike9m/pdir2#75]
I would like to work on this issue

**Comment by aqeelat** [comment]
I see that you set `requires-python = ">=3.8"`
but I guess I got confused when I saw the python 2 classifier.

Anyhow, I will cleanup the classifiers and run pyupgrade on the repo and open a PR for that.

**Comment by laike9m** [comment]
pdir2 supports Python 2 (in earlier versions) thus the classifier. I guess you can remove it.
