### ISSUE TITLE
Remove ambiguous or non-obvious names from API

### ISSUE THREAD

**Issue by mjmoore** [laike9m/pdir2#9]
.s() could mean many things: Search; splice; sort... etc. It is obvious in a limited API that .s() can probably [only mean splice](https://github.com/laike9m/pdir2/blob/master/pdir/api.py#L60), but why unnecessarily   look up the API when the code can speak for itself? 

With this, I would refer to the zen of python:

### "In the face of ambiguity, refuse the temptation to guess."

**Comment by laike9m** [comment]
You're right, but I'd rather keep it. People who favor explicitness use `search`, and those who want to save time use `s`.
